[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://point-of-sale-system-1.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

